name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop # Adjust this as per your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust this as per your project needs

      - name: Install Dependencies
        run: npm install # Or yarn install

      - name: Build Project
        run: npm run build # Adjust this to your build script

      - name: Copy Files to Root
        run: |
          cp -r ./apps/dfda-1/public/app/public/* ./

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
